source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby '3.2.2'

# Pin the reviewed CocoaPods toolchain; excluded CocoaPods releases are broken.
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
gem 'activesupport', '7.2.3.2'
gem 'xcodeproj', '1.28.1'
gem 'concurrent-ruby', '1.3.8'

# Ruby 3.4.0 has removed some libraries from the standard library.
gem 'bigdecimal', '3.2.3'
gem 'connection_pool', '2.5.4'
gem 'json', '2.19.9'
gem 'logger'
gem 'benchmark', '0.5.0'
gem 'mutex_m'
gem 'nkf', '0.2.0'
